services:
  frontend:
    build: ./elvin
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./express
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
